const kidsProducts = [
    { 
        id: 1, 
        productName: 'Kids T-Shirt', 
        description: 'Bright and fun t-shirt', 
        price: 15, 
        category: 'Kids', 
        sale: true, 
        soldOut: false,
        cover: './public/kidsarray/f80e67346645f03281ea5b8b6edd1ed1-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Cotton',
        sku: 'k1dfb'
    },
    { 
        id: 2, 
        productName: 'Kids Shorts', 
        description: 'Comfortable play shorts', 
        price: 20, 
        category: 'Kids', 
        sale: false, 
        soldOut: false,
        cover: './public/kidsarray/0a98061ea14fba285c63037947169176-removebg-preview.png',
        rating: 3,
        stock: 'inStock',
        fabric: 'Polyester',
        sku: 'k2ffx'
    },
    { 
        id: 3, 
        productName: 'Kids Hoodie', 
        description: 'Warm hoodie for winter', 
        price: 30, 
        category: 'Kids', 
        sale: true, 
        soldOut: false,
        cover: './public/kidsarray/2b88633dd193a98b1eab4b87bf54ab61-removebg-preview.png',
        rating: 5,
        stock: 'inStock',
        fabric: 'Fleece',
        sku: 'k3hxs'
    },
    { 
        id: 4, 
        productName: 'Kids Pants', 
        description: 'Stretchy pants for active kids', 
        price: 25, 
        category: 'Kids', 
        sale: false, 
        soldOut: true,
        cover: './public/kidsarray/d102853958d40dabcd7101acf4fe77a0-removebg-preview.png',
        rating: 2,
        stock: 'outOfStock',
        fabric: 'Cotton',
        sku: 'k4btq'
    },
    { 
        id: 5, 
        productName: 'Kids Jacket', 
        description: 'Waterproof jacket for rain', 
        price: 40, 
        category: 'Kids', 
        sale: false, 
        soldOut: false,
        cover: './public/kidsarray/2c3afc972ffb660d1efaf78372f229aa-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Nylon',
        sku: 'k5lzv'
    },
    { 
        id: 6, 
        productName: 'kids Sneakers', 
        description: 'Lightweight sneakers for play', 
        price: 35, 
        category: 'Kids', 
        sale: true, 
        soldOut: false,
        cover: './public/kidsarray/4b189eb83463859f7ee133dfbb9930ab-removebg-preview.png',
        rating: 5,
        stock: 'inStock',
        fabric: 'Synthetic',
        sku: 'k6qjm'
    },
    { 
        id: 7, 
        productName: 'Kids Dress', 
        description: 'Floral summer dress', 
        price: 25, 
        category: 'Kids', 
        sale: false, 
        soldOut: true,
        cover: './public/kidsarray/6d05c72f68c598bb63356021a800649e-removebg-preview.png',
        rating: 3,
        stock: 'outOfStock',
        fabric: 'Cotton',
        sku: 'k7dwf'
    },
    { 
        id: 8, 
        productName: 'Kids Cap', 
        description: 'Cool cap with cartoon print', 
        price: 10, 
        category: 'Kids', 
        sale: true, 
        soldOut: false,
        cover: './public/kidsarray/7f9a14ac74285d7f1bf4ef282edf1e78-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Cotton',
        sku: 'k8trs'
    },
    { 
        id: 9, 
        productName: 'Kids Pajamas', 
        description: 'Soft cotton pajamas', 
        price: 20, 
        category: 'Kids', 
        sale: false, 
        soldOut: false,
        cover: './public/kidsarray/80c149b2ec3e716b6487674bed641557-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Cotton',
        sku: 'k9xpl'
    },
    { 
        id: 10, 
        productName: 'Kids Boots', 
        description: 'Winter snow boots', 
        price: 45, 
        category: 'Kids', 
        sale: true, 
        soldOut: true,
        cover: './public/kidsarray/207fb772a4a1dde8c7382dd6f94aa9c3-removebg-preview.png',
        rating: 5,
        stock: 'outOfStock',
        fabric: 'Leather',
        sku: 'k10pdl'
    },
    { 
        id: 11, 
        productName: 'Kids Gloves', 
        description: 'Warm winter gloves', 
        price: 12, 
        category: 'Kids', 
        sale: false, 
        soldOut: false,
        cover: './public/kidsarray/2462b5ac13cedab114e979857bed1b61-removebg-preview.png',
        rating: 3,
        stock: 'inStock',
        fabric: 'Wool',
        sku: 'k11bzx'
    },
    { 
        id: 12, 
        productName: 'Kids Backpack', 
        description: 'Colorful school backpack', 
        price: 30, 
        category: 'Kids', 
        sale: true, 
        soldOut: false,
        cover: './public/kidsarray/9544f9c571bada35a5241d7190d0f641-removebg-preview.png',
        rating: 5,
        stock: 'inStock',
        fabric: 'Polyester',
        sku: 'k12fjn'
    },
    { 
        id: 13, 
        productName: 'Kids Socks', 
        description: 'Pack of 5 fun socks', 
        price: 10, 
        category: 'Kids', 
        sale: false, 
        soldOut: false,
        cover: './public/kidsarray/59071d6136554b95614d354b9a770895-removebg-preview.png',
        rating: 3,
        stock: 'inStock',
        fabric: 'Cotton',
        sku: 'k13gqr'
    },
    { 
        id: 14, 
        productName: 'Kids Hat', 
        description: 'Warm woolen hat', 
        price: 15, 
        category: 'Kids', 
        sale: true, 
        soldOut: false,
        cover: './public/kidsarray/3828905c8dfda2ae35eb968240387ee9-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Wool',
        sku: 'k14vcn'
    },
    { 
        id: 15, 
        productName: 'Kids Sunglasses', 
        description: 'UV protection sunglasses', 
        price: 25, 
        category: 'Kids', 
        sale: false, 
        soldOut: true,
        cover: './public/kidsarray/a172f45a733db99699364b2bde6f6534-removebg-preview.png',
        rating: 5,
        stock: 'outOfStock',
        fabric: 'Plastic',
        sku: 'k15zbf'
    },
    { 
        id: 16, 
        productName: 'Kids Raincoat', 
        description: 'Bright yellow raincoat', 
        price: 35, 
        category: 'Kids', 
        sale: true, 
        soldOut: false,
        cover: './public/kidsarray/abaa12243a9c555125a1e741e8bf4655-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Polyester',
        sku: 'k16dlm'
    },
    { 
        id: 17, 
        productName: 'Kids Swimwear', 
        description: 'Fun summer swimwear', 
        price: 20, 
        category: 'Kids', 
        sale: false, 
        soldOut: true,
        cover: './public/kidsarray/c56624cf66bd8f6667073b43d3b27110-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Polyester',
        sku: 'k16dlm'
    },
    { 
        id: 18, 
        productName: 'Kids Mittens', 
        description: 'Cute animal mittens', 
        price: 12, 
        category: 'Kids', 
        sale: true, 
        soldOut: false,
        cover: ' ./public/kidsarray/d59c9a6d19406ed17e0de25918f581eb-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Polyester',
        sku: 'k16dlm'
    }
]

export default kidsProducts;
