const menProducts = [
    { 
        id: 1, 
        productName: 'Men T-Shirt', 
        description: 'Casual cotton t-shirt', 
        price: 20, 
        category: 'Men', 
        sale: true, 
        soldOut: false,
        cover: './public/boysdata/98096da92a9dc41787a48d17615f7b80-removebg-preview.png',
        hoverImage: './public/menhover/0a5c111cbb51724cbb0c319036033cc1-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Cotton',
        sku: 'b2wnu'
    },
    { 
        id: 2, 
        productName: 'Men Jeans', 
        description: 'Comfortable blue jeans', 
        price: 50, 
        category: 'Men', 
        sale: false, 
        soldOut: false,
        cover: './public/boysdata/four-removebg-preview.png',
        hoverImage: './public/menhover/1d751b35704a05a978bacb12b264753e-removebg-preview.png',
        rating: 5,
        stock: 'inStock',
        fabric: 'Denim',
        sku: 'a3kqp'
    },
    { 
        id: 3, 
        productName: 'Men Jacket', 
        description: 'Stylish winter jacket', 
        price: 100, 
        category: 'Men', 
        sale: true, 
        soldOut: true,
        cover: './public/boysdata/5664bb692318b5c401de23099da46441-removebg-preview.png',
        hoverImage: './public/menhover/3a7ce97078a2d9fc5ca271874e682962-removebg-preview.png',
        rating: 3,
        stock: 'outOfStock',
        fabric: 'Leather',
        sku: 'm8pzs'
    },
    { 
        id: 4, 
        productName: 'Men Shorts', 
        description: 'Breathable summer shorts', 
        price: 30, 
        category: 'Men', 
        sale: false, 
        soldOut: false,
        cover: './public/boysdata/c7082f0d8ac4358cab7b151058bab39c-removebg-preview.png',
        hoverImage: './public/menhover/3a37aadac29c454ee9f53884b8a4d7be-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Polyester',
        sku: 'n5slq'
    },
    { 
        id: 5, 
        productName: 'Men Hoodie', 
        description: 'Soft hoodie for chilly days', 
        price: 40, 
        category: 'Men', 
        sale: true, 
        soldOut: false,
        cover: './public/boysdata/c242a4441aba53bc4e37c547e19199a1-removebg-preview.png',
        hoverImage: './public/menhover/026e632993af1f990aebf8eb2dd0990c-removebg-preview.png',
        rating: 5,
        stock: 'inStock',
        fabric: 'Fleece',
        sku: 'q4txb'
    },
    { 
        id: 6, 
        productName: 'Men Suit', 
        description: 'Classic formal suit', 
        price: 150, 
        category: 'Men', 
        sale: false, 
        soldOut: false,
        cover: './public/boysdata/b7ca513c809487f932e54f9547210e40-removebg-preview.png',
        hoverImage: './public/menhover/46f40eadfadff283d9997fe9e3843190-removebg-preview.png',
        rating: 4,
        stock: 'inStock',
        fabric: 'Wool',
        sku: 't7nbx'
    },
    { 
        id: 7, 
        productName: 'Men Polo Shirt', 
        description: 'Cotton polo shirt', 
        price: 25, 
        category: 'Men', 
        sale: true, 
        soldOut: false,
        cover: './public/boysdata/094722cb4cb822329c3a7869413d21a5-removebg-preview.png',
        hoverImage: './public/menhover/112dc01783b8719ab6d14078f40c4539-removebg-preview.png',
        rating: 3,
        stock: 'inStock',
        fabric: 'Cotton',
        sku: 'k3mnq'
    },
    { 
        id: 8, 
        productName: 'Men Cargo Pants', 
        description: 'Durable cargo pants', 
        price: 45, 
        category: 'Men', 
        sale: false, 
        soldOut: true,
        cover: './public/boysdata/11475c7c66252e316eaae6bc28d2a851-removebg-preview.png',
        hoverImage: './public/menhover/728cca6b0b2f456ffec81a1978a02d1e-removebg-preview.png',
        rating: 2,
        stock: 'outOfStock',
        fabric: 'Cotton',
        sku: 'x8jlm'
    },
    { 
        id: 9, 
        productName: 'Men Running Shoes', 
        description: 'Lightweight running shoes', 
        price: 60, 
        category: 'Men', 
        sale: true, 
        soldOut: false,
        cover: './public/boysdata/5664bb692318b5c401de23099da46441-removebg-preview.png',
        hoverImage: './public/menhover/947eb0729cb200205b49a776f8701659-removebg-preview.png',
        rating: 5,
        stock: 'inStock',
        fabric: 'Synthetic',
        sku: 'z9yxw'
    },
    { 
        id: 10, 
        productName: 'Men Leather Jacket', 
        description: 'Genuine leather jacket', 
        price: 200, 
        category: 'Men', 
        sale: false, 
        soldOut: true,
        cover: './public/boysdata/85f3237f4f1f194d8b6c688beeed44c5-removebg-preview.png',
        hoverImage: './public/menhover/bd8d40fc372843e0df738ce49b02ba9c-removebg-preview.png',
        rating: 4,
        stock: 'outOfStock',
        fabric: 'Leather',
        sku: 'y4plk'
    },
    // Continue updating the remaining objects similarly
];

export default menProducts;
