const womenProducts = [

        { 
            id: 1, 
            productName: 'Women Dress', 
            description: 'Elegant red evening dress', 
            price: 80, 
            category: 'Women', 
            sale: true, 
            soldOut: false,
            cover: './public/womenarray/0aa48ca9d081f2988a2749408a30d24b-removebg-preview.png',
            hoverImage: './public/womenshover/0bde978ed3bc09e466c7bbf54746c71a-removebg-preview.png',
            rating: 4,
            stocks: 'instock',
            fabric: 'Silk',
            sku: 'b2wnu'
        },
        { 
            id: 2, 
            productName: 'Women Blouse', 
            description: 'Lightweight summer blouse', 
            price: 40, 
            category: 'Women', 
            sale: false, 
            soldOut: true,
            cover: './public/womenarray/1a90217dfdea78921cbc8aa716f875be-removebg-preview.png',
            hoverImage: './public/womenshover/0c4dc6a88ec898594405248a22f60eb3-removebg-preview (1).png',
            rating: 5,
            stocks: 'outofstock',
            fabric: 'Cotton',
            sku: 'd9rhv'
        },
        { 
            id: 3, 
            productName: 'Women Jeans', 
            description: 'High-rise skinny jeans', 
            price: 60, 
            category: 'Women', 
            sale: true, 
            soldOut: false,
            cover: './public/womenarray/3a8cc4ae2779f753b1aae9bf26567caf-removebg-preview.png',
            hoverImage: './public/womenshover/0c4dc6a88ec898594405248a22f60eb3-removebg-preview.png',
            rating: 3,
            stocks: 'instock',
            fabric: 'Denim',
            sku: 'k7mhs'
        },
        { 
            id: 4, 
            productName: 'Women Skirt', 
            description: 'Floral print mini skirt', 
            price: 35, 
            category: 'Women', 
            sale: false, 
            soldOut: false,
            cover: './public/womenarray/4be5014bb7d4fb08035d978f7a2da06d-removebg-preview.png',
            hoverImage: './public/womenshover/9b7df56a8e3e1480e52144acca7d3b6d-removebg-preview.png',
            rating: 4,
            stocks: 'instock',
            fabric: 'Linen',
            sku: 'n2qza'
        },
        { 
            id: 5, 
            productName: 'Women Jacket', 
            description: 'Leather jacket', 
            price: 120, 
            category: 'Women', 
            sale: false, 
            soldOut: true,
            cover: './public/womenarray/7f981ef916ec342bbaae15f5ba556c99-removebg-preview (1).png',
            hoverImage: './public/womenshover/14e2960100a3e3058c13f922801c45d7-removebg-preview.png',
            rating: 5,
            stocks: 'outofstock',
            fabric: 'Leather',
            sku: 'y5lki'
        },
        { 
            id: 6, 
            productName: 'Women Cardigan', 
            description: 'Wool blend long cardigan', 
            price: 55, 
            category: 'Women', 
            sale: true, 
            soldOut: false,
            cover: './public/womenarray/8c83132f71d3414f5bef424ba84d5f99-removebg-preview.png',
            hoverImage: './public/womenshover/32d964f609bf7f0ab0dc74f1a1ec5f45-removebg-preview.png',
            rating: 4,
            stocks: 'instock',
            fabric: 'Wool',
            sku: 'p4juz'
        },
        { 
            id: 7, 
            productName: 'Women Sandals', 
            description: 'Open-toe summer sandals', 
            price: 25, 
            category: 'Women', 
            sale: false, 
            soldOut: true,
            cover: './public/womenarray/57d6638ad28ef7ef5ac470159b2eb45b-removebg-preview.png',
            hoverImage: './public/womenshover/649f3014cb4a304ec42286662a341082-removebg-preview.png',
            rating: 3,
            stocks: 'outofstock',
            fabric: 'Leather',
            sku: 'z8jkp'
        },
        { 
            id: 8, 
            productName: 'Women Sunglasses', 
            description: 'Oversized sunglasses', 
            price: 50, 
            category: 'Women', 
            sale: true, 
            soldOut: false,
            cover: './public/womenarray/766a1d38eeabf3477e3e03db033cd74c-removebg-preview.png',
            hoverImage: './public/womenshover/967f811481efaf58484c8d6f836ec44a-removebg-preview.png',
            rating: 5,
            stocks: 'instock',
            fabric: 'Plastic',
            sku: 't6vdm'
        },
        { 
            id: 9, 
            productName: 'Women Handbag', 
            description: 'Leather crossbody handbag', 
            price: 85, 
            category: 'Women', 
            sale: false, 
            soldOut: false,
            cover: './public/womenarray/9781e7de84c94942e2b8d35ff4b8ba5b-removebg-preview.png',
            hoverImage: './public/womenshover/982d9d94f385d703bd7285f35c920e3b-removebg-preview.png',
            rating: 4,
            stocks: 'instock',
            fabric: 'Leather',
            sku: 'm4gty'
        },
        { 
            id: 10, 
            productName: 'Women Heels', 
            description: 'Stiletto high heels', 
            price: 95, 
            category: 'Women', 
            sale: true, 
            soldOut: true,
            cover: './public/womenarray/78668d841c10dfc7bd1d5238d8bf1f26-removebg-preview.png',
            hoverImage: './public/womenshover/203136b25937a23350c881e1c935d3ac-removebg-preview.png',
            rating: 5,
            stocks: 'outofstock',
            fabric: 'Leather',
            sku: 'b7eip'
        },
        { 
            id: 11, 
            productName: 'Women Boots', 
            description: 'Knee-high leather boots', 
            price: 150, 
            category: 'Women', 
            sale: false, 
            soldOut: false,
            cover: './public/womenarray/a80e7617b65501e6123539f6c02bf927-removebg-preview.png',
            hoverImage: './public/womenshover/65384646edd40d2aa2d854677f8adb08-removebg-preview.png',
            rating: 4,
            stocks: 'instock',
            fabric: 'Leather',
            sku: 'g9fhx'
        },
        { 
            id: 12, 
            productName: 'Women Sweater', 
            description: 'Cashmere crewneck sweater', 
            price: 100, 
            category: 'Women', 
            sale: true, 
            soldOut: false,
            cover: './public/womenarray/c2a1630ff89b708f8f32312ddfd615c4-removebg-preview (1).png',
            hoverImage: './public/womenshover/bee578ccce4908d4ac33febbe355459a-removebg-preview.png',
            rating: 5,
            stocks: 'instock',
            fabric: 'Cashmere',
            sku: 'x3jht'
        },
        { 
            id: 13, 
            productName: 'Women Coat', 
            description: 'Long wool coat', 
            price: 180, 
            category: 'Women', 
            sale: false, 
            soldOut: false,
            cover: './public/womenarray/c4d0f1ccdf88eb43562065ccf04bfb8a-removebg-preview.png',
            hoverImage: './public/womenshover/c880025ba13635dcd651039415bd414e-removebg-preview.png',
            rating: 5,
            stocks: 'instock',
            fabric: 'Wool',
            sku: 'l7bdf'
        },
        { 
            id: 14, 
            productName: 'Women Scarf', 
            description: 'Silk neck scarf', 
            price: 25, 
            category: 'Women', 
            sale: true, 
            soldOut: true,
            cover: './public/womenarray/cbfdb8e1e37cb4a6b6e4fb4539f55c4c-removebg-preview.png',
            hoverImage: './public/womenshover/ccd76e79d9d64f369a97fd27dc64feab-removebg-preview.png',
            rating: 4,
            stocks: 'outofstock',
            fabric: 'Silk',
            sku: 'v3pld'
        },

    
    { 
        id: 15, 
        productName: 'Women Hat', 
        description: 'Wide-brim sun hat', 
        price: 40, 
        category: 'Women', 
        sale: false, 
        soldOut: true,
        cover: './public/womenarray/d626ea61b3fe3d13a44f517254aed477-removebg-preview.png',
        hoverImage: '  ./public/womenshover/d2103f8bd2ef1283b3564ac4f20628df-removebg-preview.png',
        rating: 4,
        stocks: 'outofstock',
        fabric: 'Silk',
        sku: 'v3pld' // Placeholder for hover image
    },
    { 
        id: 16, 
        productName: 'Women Flats', 
        description: 'Comfortable ballet flats', 
        price: 60, 
        category: 'Women', 
        sale: true, 
        soldOut: false,
        cover: './public/womenarray/ddf1fa8c8bf4b7240f8735e7fe870d45-removebg-preview.png',
        hoverImage: '  ./public/womenshover/04b0ca176e7d6a9fae3ebcb1a0392899-removebg-preview.png',
        rating: 4,
        stocks: 'outofstock',
        fabric: 'Silk',
        sku: 'v3pld' // Placeholder for hover image
    },
];

export default womenProducts;
